name: Job listing CI/CD practice

on: 
  push:
    branches: 
      - main
jobs: 
  deploy: 
    runs-on: ubuntu-latest 

    steps: 
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: action/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
